'use client';
import { useEffect, useRef, useState, useCallback } from 'react';

/**
 * The page reads itself. Audio was generated by the same Kokoro model the
 * extension runs, so the voice on this page IS the product.
 *
 * Two things live here:
 *   1. the narration clock — which sentence is lit, driven off <audio>.currentTime
 *   2. the bird — a flipbook of eight watercolour frames that flies in on load,
 *      fidgets while idle, sings while the page narrates, and leaves when it ends
 */

// frame number -> file. Frames 2–7 share the same twig position and scale.
const FRAMES = [
  '1-flight', '2-landing', '3-perched', '4-tilt',
  '5-sing-open', '6-sing-closed', '7-preen', '8-flyaway',
];
const FLIGHT = 1, LANDING = 2, PERCHED = 3, TILT = 4,
      SING_OPEN = 5, SING_CLOSED = 6, PREEN = 7, FLYAWAY = 8;

// The birdsong bed: a loop of public-domain chickadee recordings, played through
// Web Audio so it can be faded rather than switched. It sits under everything
// and ducks while the narration speaks.
const BED_LEVEL = 0.55, DUCK_LEVEL = 0.13, BED_KEY = 'chickadee.birdsong';

export default function Narrator({ sentences, total }) {
  const audioRef = useRef(null);
  const rafRef = useRef(0);
  const idxRef = useRef(-1);      // read inside rAF without re-arming the loop
  const lastTick = useRef(0);

  const hero = sentences.filter((s) => s.zone === 'hero');
  const sub  = sentences.filter((s) => s.zone === 'sub');
  const body = sentences.filter((s) => s.zone === 'body');
  const heroCount = hero.length;
  const subCount = sub.length;

  const [playing, setPlaying] = useState(false);
  const [idx, setIdx] = useState(-1);
  const [elapsed, setElapsed] = useState(0);

  /* ---- the birdsong bed ---- */
  const ac = useRef(null);          // AudioContext, created on mount, running after a gesture
  const bedGain = useRef(null);
  const bedBuf = useRef(null);
  const bedSrc = useRef(null);
  const bedTarget = useRef(BED_LEVEL);
  const wantBed = useRef(true);     // the user's preference
  const [birdsong, setBirdsong] = useState('waiting');   // 'waiting' | 'on' | 'off'

  const fadeBed = useCallback((level, seconds) => {
    const g = bedGain.current, ctx = ac.current;
    if (!g || !ctx) return;
    const t = ctx.currentTime;
    g.gain.cancelScheduledValues(t);
    g.gain.setValueAtTime(g.gain.value, t);
    g.gain.linearRampToValueAtTime(level, t + seconds);
  }, []);
  // the level the bed should sit at right now, given what the page is doing
  const settleBed = useCallback((seconds) => {
    fadeBed(bedTarget.current, seconds);
  }, [fadeBed]);

  const startBed = useCallback(async () => {
    if (!wantBed.current) return;
    try {
      if (!ac.current) {
        const AC = window.AudioContext || window.webkitAudioContext;
        if (!AC) return;
        ac.current = new AC();
        bedGain.current = ac.current.createGain();
        bedGain.current.gain.value = 0;
        bedGain.current.connect(ac.current.destination);
      }
      if (!bedBuf.current) {
        const res = await fetch('/audio/birdsong.mp3');
        bedBuf.current = await ac.current.decodeAudioData(await res.arrayBuffer());
      }
      if (!wantBed.current) return;                 // switched off while loading
      // Autoplay policy: resume() only succeeds once the visitor has interacted
      // with the page. If it stays suspended we wait for the first gesture.
      await ac.current.resume();
      if (ac.current.state !== 'running') return;
      if (!bedSrc.current) {
        const src = ac.current.createBufferSource();
        src.buffer = bedBuf.current;
        src.loop = true;
        src.connect(bedGain.current);
        // start somewhere in the loop so a reload does not replay the same minute
        src.start(0, Math.random() * bedBuf.current.duration);
        bedSrc.current = src;
      }
      setBirdsong('on');
      settleBed(3);
    } catch (e) { /* no audio, no bed — the page still works */ }
  }, [settleBed]);

  const toggleBirdsong = () => {
    if (birdsong === 'on') {
      wantBed.current = false;
      fadeBed(0, 1.2);
      setBirdsong('off');
      try { localStorage.setItem(BED_KEY, 'off'); } catch {}
    } else {
      wantBed.current = true;
      try { localStorage.setItem(BED_KEY, 'on'); } catch {}
      startBed();
    }
  };

  useEffect(() => {
    let pref = null;
    try { pref = localStorage.getItem(BED_KEY); } catch {}
    if (pref === 'off') { wantBed.current = false; setBirdsong('off'); }
    else startBed();
    // the first click, tap or key anywhere lets the birdsong in
    const gesture = () => { if (wantBed.current && !bedSrc.current) startBed(); };
    window.addEventListener('pointerdown', gesture);
    window.addEventListener('keydown', gesture);
    // hidden tabs go quiet; coming back fades the bed in again
    const vis = () => {
      if (!bedSrc.current) return;
      if (document.hidden) fadeBed(0, 0.8); else if (wantBed.current) settleBed(2.5);
    };
    document.addEventListener('visibilitychange', vis);
    return () => {
      window.removeEventListener('pointerdown', gesture);
      window.removeEventListener('keydown', gesture);
      document.removeEventListener('visibilitychange', vis);
      if (ac.current) { try { ac.current.close(); } catch {} }
    };
  }, [startBed, fadeBed, settleBed]);

  /* ---- the bird ---- */
  const [bird, setBirdState] = useState(FLIGHT);
  const birdRef = useRef(FLIGHT);
  const playingRef = useRef(false);
  const timers = useRef(new Set());   // one-shot timeouts, all cleared on unmount
  const singRef = useRef(0);
  const idleRef = useRef(0);
  const reduced = useRef(false);

  const setBird = useCallback((f) => {
    if (birdRef.current === f) return;
    birdRef.current = f; setBirdState(f);
  }, []);
  const after = useCallback((ms, fn) => {
    const t = setTimeout(() => { timers.current.delete(t); fn(); }, ms);
    timers.current.add(t);
  }, []);

  // 1 at 0ms -> 2 at 800ms -> 3 at 1500ms
  const flyIn = useCallback(() => {
    if (reduced.current) { setBird(PERCHED); return; }
    setBird(FLIGHT);
    after(800, () => setBird(LANDING));
    after(1500, () => setBird(PERCHED));
  }, [after, setBird]);

  // while idle: every 3.8–6.8s, a head tilt or a preen, then back to the perch
  const idle = useCallback(() => {
    if (!playingRef.current && birdRef.current === PERCHED) {
      const f = Math.random() < 0.5 ? TILT : PREEN;
      setBird(f);
      after(f === PREEN ? 900 : 520, () => {
        if (!playingRef.current && birdRef.current === f) setBird(PERCHED);
      });
    }
    idleRef.current = setTimeout(idle, 3800 + Math.random() * 3000);
  }, [after, setBird]);

  const startSinging = useCallback(() => {
    clearInterval(singRef.current);
    setBird(SING_OPEN);
    singRef.current = setInterval(() => {
      setBird(birdRef.current === SING_OPEN ? SING_CLOSED : SING_OPEN);
    }, 360);
  }, [setBird]);
  const stopSinging = useCallback(() => {
    clearInterval(singRef.current);
    singRef.current = 0;
  }, []);

  useEffect(() => {
    reduced.current = !!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
    flyIn();
    // idle loop starts 3.5s after landing
    idleRef.current = setTimeout(idle, (reduced.current ? 0 : 1500) + 3500);
    const t = timers.current;
    return () => {
      t.forEach(clearTimeout); t.clear();
      clearTimeout(idleRef.current);
      clearInterval(singRef.current);
    };
  }, [flyIn, idle]);

  /* ---- the clock ---- */
  useEffect(() => {
    const tick = () => {
      const a = audioRef.current;
      if (a && !a.paused) {
        const t = a.currentTime;
        if (t - lastTick.current > 0.25) { lastTick.current = t; setElapsed(t); }
        const i = sentences.findIndex((s) => t >= s.start && t < s.end);
        if (i !== idxRef.current) { idxRef.current = i; setIdx(i); }
      }
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, [sentences]);   // NOT idx — that rebuilt the loop mid-speech

  const toggle = async () => {
    const a = audioRef.current;
    if (!a) return;
    if (a.paused) {
      idxRef.current = -1;
      await a.play();
      playingRef.current = true; setPlaying(true);
      startSinging();
      bedTarget.current = DUCK_LEVEL; settleBed(1.2);   // the birds hush for the voice
    } else {
      a.pause();
      playingRef.current = false; setPlaying(false);
      stopSinging(); setBird(PERCHED);
      bedTarget.current = BED_LEVEL; settleBed(2.5);
    }
  };

  const seek = (i) => {
    const a = audioRef.current; if (!a) return;
    a.currentTime = sentences[i].start + 0.01;
    if (a.paused) toggle();
  };

  const ended = () => {
    playingRef.current = false; setPlaying(false);
    setIdx(-1); idxRef.current = -1; setElapsed(0); lastTick.current = 0;
    stopSinging();
    bedTarget.current = BED_LEVEL; settleBed(3.5);
    if (reduced.current) { setBird(PERCHED); return; }
    setBird(FLYAWAY);
    after(2600, flyIn);
  };

  // Idle pages read as normal pages. Dimming only makes sense once there is a
  // "current" sentence to contrast against.
  const reading = playing || idx >= 0;

  const mmss = (s) => `${Math.floor(s / 60)}:${String(Math.floor(s % 60)).padStart(2, '0')}`;
  const sentClass = (i) => `sent${idx === i ? ' live' : ''}`;

  return (
    <>
      <section className={`hero${reading ? ' reading' : ''}`}>
        <div className="hero__copy">
          <h1>
            {hero.map((s, i) => (
              <span key={i}>
                <span className={sentClass(i)} onClick={() => seek(i)}>{s.text}</span>
                {i < hero.length - 1 ? <br /> : null}
              </span>
            ))}
          </h1>
          <p className="standfirst">
            {sub.map((s, k) => {
              const i = k + heroCount;
              return (
                <span key={i} className={sentClass(i)} onClick={() => seek(i)} title="Read from here">
                  {s.text}{' '}
                </span>
              );
            })}
          </p>
          <div className="controls">
            <button className="btn listen" onClick={toggle}>{playing ? 'Pause' : 'Listen'}</button>
            <span className="elapsed">
              {mmss(elapsed)} / {mmss(total)} — {playing ? 'speaking' : 'the page reads itself'}
            </span>
            <button type="button" className={`birdsong birdsong--${birdsong}`} onClick={toggleBirdsong}
                    aria-pressed={birdsong === 'on'}
                    title={birdsong === 'on' ? 'Quiet the birds' : 'Let the birds in'}>
              {birdsong === 'on' ? '♪ birdsong on' : birdsong === 'off' ? '♪ birdsong off' : '♪ birdsong — click anywhere to hear'}
            </button>
          </div>
        </div>

        <figure className="bird">
          <div className="bird__box" role="img"
               aria-label={playing ? 'A watercolour chickadee on a twig, singing' : 'A watercolour chickadee on a twig, listening'}>
            {FRAMES.map((f, n) => (
              <div key={f} aria-hidden="true"
                   className={`bird__frame bird__frame--${n + 1}${bird === n + 1 ? ' on' : ''}`}
                   style={{ backgroundImage: `url(/birds/${f}.webp)` }} />
            ))}
          </div>
          <figcaption>{playing ? 'fig. 1 — chickadee, singing' : 'fig. 1 — chickadee, listening'}</figcaption>
        </figure>
      </section>

      <section className={`passage${reading ? ' reading' : ''}`}>
        <div className={`label${playing ? ' live' : ''}`}>
          <span className="dot" />
          {playing ? 'now speaking — Kokoro-82M, voice af_heart' : 'press listen. the page will read itself.'}
        </div>

        <p className="script">
          {body.map((s, k) => {
            const i = k + heroCount + subCount;
            return (
              <span key={i} className={sentClass(i)} onClick={() => seek(i)} title="Read from here">
                {s.text}{' '}
              </span>
            );
          })}
        </p>

        <audio ref={audioRef} src="/audio/narration.mp3" preload="auto" onEnded={ended} />
      </section>
    </>
  );
}
