'use client';
import { useEffect, useRef, useState, useCallback } from 'react';

/**
 * The page reads itself. Audio was generated by the same Kokoro model the
 * extension runs, so the voice on this page IS the product.
 *
 * Two things live here:
 *   1. the narration clock — which sentence is lit, driven off <audio>.currentTime
 *   2. the bird — a flipbook of eight watercolour frames that flies in on load,
 *      fidgets while idle, sings while the page narrates, and leaves when it ends
 */

// frame number -> file. Frames 2–7 share the same twig position and scale.
const FRAMES = [
  '1-flight', '2-landing', '3-perched', '4-tilt',
  '5-sing-open', '6-sing-closed', '7-preen', '8-flyaway',
];
const FLIGHT = 1, LANDING = 2, PERCHED = 3, TILT = 4,
      SING_OPEN = 5, SING_CLOSED = 6, PREEN = 7, FLYAWAY = 8;

// Two phrases get a watercolour wash that spreads under them as they are spoken.
// Everything else just lifts back to full ink while the rest of the page dims.
const WASHED = new Set(['read aloud,', "Chickadee doesn't."]);

// The birdsong bed: a loop of public-domain chickadee recordings, played through
// Web Audio so it can be faded rather than switched. It sits under everything
// and ducks while the narration speaks.
const BED_LEVEL = 0.55, DUCK_LEVEL = 0.13, BED_KEY = 'chickadee.birdsong';

export default function Narrator({ sentences, total }) {
  const audioRef = useRef(null);
  const rafRef = useRef(0);
  const idxRef = useRef(-1);      // read inside rAF without re-arming the loop
  const lastTick = useRef(0);
  const washRefs = useRef({});    // sentence index -> element, for the spreading wash
  const sentRefs = useRef({});    // sentence index -> element, for following the voice
  const sectionRefs = useRef({}); // section name -> element, for arriving at each section

  // every sentence carries a zone (one per element on the page); zones roll up
  // into the sections the page scrolls between
  const zone = (z) => sentences.map((s, i) => [s, i]).filter(([s]) => s.zone === z);
  const sectionOf = (z) => (z === 'hero' || z === 'sub') ? 'hero' : z === 'body' ? 'passage' : z.split('-')[0];

  const [playing, setPlaying] = useState(false);
  const [idx, setIdx] = useState(-1);
  const [elapsed, setElapsed] = useState(0);

  /* ---- the birdsong bed ---- */
  const ac = useRef(null);          // AudioContext, created on mount, running after a gesture
  const bedGain = useRef(null);
  const bedBuf = useRef(null);
  const bedSrc = useRef(null);
  const bedTarget = useRef(BED_LEVEL);
  const wantBed = useRef(true);     // the user's preference
  // 'waiting' is on, but blocked by the browser until the visitor's first click or key
  const [birdsong, setBirdsong] = useState('waiting');   // 'waiting' | 'on' | 'off'

  const fadeBed = useCallback((level, seconds) => {
    const g = bedGain.current, ctx = ac.current;
    if (!g || !ctx) return;
    const t = ctx.currentTime;
    g.gain.cancelScheduledValues(t);
    g.gain.setValueAtTime(g.gain.value, t);
    g.gain.linearRampToValueAtTime(level, t + seconds);
  }, []);
  // the level the bed should sit at right now, given what the page is doing
  const settleBed = useCallback((seconds) => {
    fadeBed(bedTarget.current, seconds);
  }, [fadeBed]);

  const startBed = useCallback(async () => {
    if (!wantBed.current) return;
    try {
      if (!ac.current) {
        const AC = window.AudioContext || window.webkitAudioContext;
        if (!AC) return;
        ac.current = new AC();
        bedGain.current = ac.current.createGain();
        bedGain.current.gain.value = 0;
        bedGain.current.connect(ac.current.destination);
      }
      if (!bedBuf.current) {
        const res = await fetch('/audio/birdsong.mp3');
        bedBuf.current = await ac.current.decodeAudioData(await res.arrayBuffer());
      }
      if (!wantBed.current) return;                 // switched off while loading
      // Autoplay policy: resume() only succeeds once the visitor has interacted
      // with the page. If it stays suspended we wait for the first gesture.
      await ac.current.resume();
      if (ac.current.state !== 'running') return;
      if (!bedSrc.current) {
        const src = ac.current.createBufferSource();
        src.buffer = bedBuf.current;
        src.loop = true;
        src.connect(bedGain.current);
        // start somewhere in the loop so a reload does not replay the same minute
        src.start(0, Math.random() * bedBuf.current.duration);
        bedSrc.current = src;
      }
      setBirdsong('on');
      settleBed(3);
    } catch (e) { /* no audio, no bed — the page still works */ }
  }, [settleBed]);

  const toggleBirdsong = () => {
    if (birdsong === 'on') {
      wantBed.current = false;
      fadeBed(0, 1.2);
      setBirdsong('off');
      try { localStorage.setItem(BED_KEY, 'off'); } catch {}
    } else {
      wantBed.current = true;
      try { localStorage.setItem(BED_KEY, 'on'); } catch {}
      startBed();
    }
  };

  useEffect(() => {
    let pref = null;
    try { pref = localStorage.getItem(BED_KEY); } catch {}
    if (pref === 'off') { wantBed.current = false; setBirdsong('off'); }
    else startBed();
    // the first click, tap or key anywhere lets the birdsong in
    const gesture = () => { if (wantBed.current && !bedSrc.current) startBed(); };
    window.addEventListener('pointerdown', gesture);
    window.addEventListener('keydown', gesture);
    // hidden tabs go quiet; coming back fades the bed in again
    const vis = () => {
      if (!bedSrc.current) return;
      if (document.hidden) fadeBed(0, 0.8); else if (wantBed.current) settleBed(2.5);
    };
    document.addEventListener('visibilitychange', vis);
    return () => {
      window.removeEventListener('pointerdown', gesture);
      window.removeEventListener('keydown', gesture);
      document.removeEventListener('visibilitychange', vis);
      if (ac.current) { try { ac.current.close(); } catch {} }
    };
  }, [startBed, fadeBed, settleBed]);

  /* ---- the bird ---- */
  const [bird, setBirdState] = useState(FLIGHT);
  const birdRef = useRef(FLIGHT);
  const playingRef = useRef(false);
  const timers = useRef(new Set());   // one-shot timeouts, all cleared on unmount
  const singRef = useRef(0);
  const idleRef = useRef(0);
  const reduced = useRef(false);

  const setBird = useCallback((f) => {
    if (birdRef.current === f) return;
    birdRef.current = f; setBirdState(f);
  }, []);
  const after = useCallback((ms, fn) => {
    const t = setTimeout(() => { timers.current.delete(t); fn(); }, ms);
    timers.current.add(t);
  }, []);

  // 1 at 0ms -> 2 at 800ms -> 3 at 1500ms
  const flyIn = useCallback(() => {
    if (reduced.current) { setBird(PERCHED); return; }
    setBird(FLIGHT);
    after(800, () => setBird(LANDING));
    after(1500, () => setBird(PERCHED));
  }, [after, setBird]);

  // while idle: every 3.8–6.8s, a head tilt or a preen, then back to the perch
  const idle = useCallback(() => {
    if (!playingRef.current && birdRef.current === PERCHED) {
      const f = Math.random() < 0.5 ? TILT : PREEN;
      setBird(f);
      after(f === PREEN ? 900 : 520, () => {
        if (!playingRef.current && birdRef.current === f) setBird(PERCHED);
      });
    }
    idleRef.current = setTimeout(idle, 3800 + Math.random() * 3000);
  }, [after, setBird]);

  const startSinging = useCallback(() => {
    clearInterval(singRef.current);
    setBird(SING_OPEN);
    singRef.current = setInterval(() => {
      setBird(birdRef.current === SING_OPEN ? SING_CLOSED : SING_OPEN);
    }, 360);
  }, [setBird]);
  const stopSinging = useCallback(() => {
    clearInterval(singRef.current);
    singRef.current = 0;
  }, []);

  useEffect(() => {
    reduced.current = !!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
    flyIn();
    // idle loop starts 3.5s after landing
    idleRef.current = setTimeout(idle, (reduced.current ? 0 : 1500) + 3500);
    const t = timers.current;
    return () => {
      t.forEach(clearTimeout); t.clear();
      clearTimeout(idleRef.current);
      clearInterval(singRef.current);
    };
  }, [flyIn, idle]);

  // The page follows the voice: when the live sentence has left the comfortable
  // band of the viewport, scroll so it sits a third of the way down. Entering the
  // passage scrolls to its label instead, so the section arrives as a whole.
  const follow = useCallback((i) => {
    if (i < 0) return;
    const sec = sectionOf(sentences[i].zone);
    const entering = sec !== 'hero' && (i === 0 || sectionOf(sentences[i - 1].zone) !== sec);
    const el = entering ? sectionRefs.current[sec] : sentRefs.current[i];
    if (!el) return;
    const r = el.getBoundingClientRect();
    const inBand = r.top >= 72 && r.bottom <= innerHeight - 120;
    if (inBand && !entering) return;
    const top = scrollY + r.top - innerHeight * (entering ? 0.12 : 0.3);
    scrollTo({ top: Math.max(0, top), behavior: reduced.current ? 'auto' : 'smooth' });
  }, [sentences]);

  /* ---- the clock ---- */
  useEffect(() => {
    const tick = () => {
      const a = audioRef.current;
      if (a && !a.paused) {
        const t = a.currentTime;
        if (t - lastTick.current > 0.25) { lastTick.current = t; setElapsed(t); }
        const i = sentences.findIndex((s) => t >= s.start && t < s.end);
        if (i !== idxRef.current) { idxRef.current = i; setIdx(i); follow(i); }
        // the wash spreads at the speaking rate, straight off the clock via refs,
        // so it never waits on a React render
        for (const [k, el] of Object.entries(washRefs.current)) {
          if (!el) continue;
          const s = sentences[k];
          const p = t < s.start ? 0 : t >= s.end ? 1 : (t - s.start) / (s.end - s.start);
          el.style.setProperty('--p', `${(p * 118).toFixed(1)}%`);
        }
      }
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, [sentences, follow]);   // NOT idx — that rebuilt the loop mid-speech

  const toggle = async () => {
    const a = audioRef.current;
    if (!a) return;
    if (a.paused) {
      idxRef.current = -1;
      await a.play();
      playingRef.current = true; setPlaying(true);
      startSinging();
      bedTarget.current = DUCK_LEVEL; settleBed(1.2);   // the birds hush for the voice
    } else {
      a.pause();
      playingRef.current = false; setPlaying(false);
      stopSinging(); setBird(PERCHED);
      bedTarget.current = BED_LEVEL; settleBed(2.5);
    }
  };

  const seek = (i) => {
    const a = audioRef.current; if (!a) return;
    a.currentTime = sentences[i].start + 0.01;
    if (a.paused) toggle();
  };

  const ended = () => {
    playingRef.current = false; setPlaying(false);
    setIdx(-1); idxRef.current = -1; setElapsed(0); lastTick.current = 0;
    stopSinging();
    bedTarget.current = BED_LEVEL; settleBed(3.5);
    after(900, () => { for (const el of Object.values(washRefs.current)) el && el.style.setProperty('--p', '0%'); });
    if (reduced.current) { setBird(PERCHED); return; }
    setBird(FLYAWAY);
    after(2600, flyIn);
  };

  // Idle pages read as normal pages. Dimming only makes sense once there is a
  // "current" sentence to contrast against.
  const reading = playing || idx >= 0;

  const mmss = (s) => `${Math.floor(s / 60)}:${String(Math.floor(s % 60)).padStart(2, '0')}`;
  const sentClass = (i) => {
    const washed = WASHED.has(sentences[i].text);
    return `sent${washed ? ' washed' : ''}${idx === i ? ' live' : ''}${washed && idx > i ? ' spoken' : ''}`;
  };
  const washRef = (i) => (el) => {
    sentRefs.current[i] = el;
    if (WASHED.has(sentences[i].text)) washRefs.current[i] = el;
  };
  const secRef = (name) => (el) => { sectionRefs.current[name] = el; };
  // "⌥ R" is set in italic inside the install heading
  const inline = (text) => {
    const k = text.indexOf('⌥ R');
    if (k < 0) return text;
    return (<>{text.slice(0, k)}<em>⌥ R</em>{text.slice(k + 3)}</>);
  };
  // the sentences of one zone, each clickable and lit by the clock
  const spans = (z, sep = ' ') => zone(z).map(([s, i], k, arr) => (
    <span key={i}>
      <span className={sentClass(i)} ref={washRef(i)} onClick={() => seek(i)} title="Read from here">{inline(s.text)}</span>
      {k < arr.length - 1 ? sep : null}
    </span>
  ));
  const rd = reading ? ' reading' : '';

  const birdsongLabel = birdsong === 'off' ? 'Birdsong off — let the birds in' : 'Birdsong on — quiet the birds';

  return (
    <>
      <header className="mast">
        <img className="mast__logo" src="/birds/head-right.webp" alt="" width="48" height="48" />
        <span className="word">Chickadee</span>
        <span className="note">runs entirely on your machine</span>
        <span className="mast__right">
        <span className="meta">Local · Open source · Free forever</span>
        <button type="button" className={`birdsong birdsong--${birdsong}`} onClick={toggleBirdsong}
                aria-pressed={birdsong !== 'off'} aria-label={birdsongLabel} title={birdsongLabel}>
          <svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor"
               strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            <path d="M9.5 18V5.8l9-2.2v11.2" />
            <ellipse cx="7" cy="18.2" rx="2.6" ry="1.9" />
            <ellipse cx="16" cy="15" rx="2.6" ry="1.9" />
            {birdsong === 'off' ? <path className="birdsong__strike" d="M4.5 4.5l15 15" /> : null}
          </svg>
        </button>
        </span>
      </header>

      <section className={`hero${rd}`} ref={secRef('hero')}>
        <div className="hero__copy">
          <h1>
            {zone('hero').map(([s, i], k, arr) => (
              <span key={i}>
                <span className={sentClass(i)} ref={washRef(i)} onClick={() => seek(i)}>{s.text}</span>
                {k < arr.length - 1 ? <br /> : null}
              </span>
            ))}
          </h1>
          <p className="standfirst">{spans('sub')}</p>
          <div className="controls">
            <button className="btn listen" onClick={toggle}>{playing ? 'Pause' : 'Listen'}</button>
            <span className="elapsed">
              {mmss(elapsed)} / {mmss(total)} — {playing ? 'speaking' : 'the page reads itself'}
            </span>
          </div>
        </div>

        <figure className="bird">
          <div className="bird__box" role="img"
               aria-label={playing ? 'A watercolour chickadee on a twig, singing' : 'A watercolour chickadee on a twig, listening'}>
            {FRAMES.map((f, n) => (
              <div key={f} aria-hidden="true"
                   className={`bird__frame bird__frame--${n + 1}${bird === n + 1 ? ' on' : ''}`}
                   style={{ backgroundImage: `url(/birds/${f}.webp)` }} />
            ))}
          </div>
          <figcaption>{playing ? 'fig. 1 — chickadee, singing' : 'fig. 1 — chickadee, listening'}</figcaption>
        </figure>
      </section>

      <section className={`passage${rd}`} ref={secRef('passage')}>
        <div className={`label${playing ? ' live' : ''}`}>
          <span className="dot" />
          {playing ? 'now speaking — Kokoro-82M, voice af_heart' : 'press listen. the page will read itself.'}
        </div>
        <p className="script">{spans('body')}</p>
        <audio ref={audioRef} src="/audio/narration.mp3" preload="auto" onEnded={ended} />
      </section>

      {/* fig. 2 — one real capture, taped into the sketchbook */}
      <section className={`showcase${rd}`} ref={secRef('showcase')}>
        <div className="wash wash--sky" aria-hidden="true" />
        <div>
          <span className="fig">fig. 2 — seeing it work</span>
          <h2>{spans('showcase-h')}</h2>
          <p>{spans('showcase-p')}</p>
        </div>
        <figure className="print">
          <div className="tape" aria-hidden="true" />
          <img src="/shots/shot-dark.png"
               alt="Chickadee reading an essay: the sentence currently being spoken is highlighted directly on the page" />
          <figcaption>darioamodei.com/essay/machines-of-loving-grace</figcaption>
        </figure>
      </section>

      <section className={`proof${rd}`} ref={secRef('proof')}>
        <img className="sketch" src="/birds/head-study.webp" alt="" aria-hidden="true" />
        {[1, 2, 3, 4].map((n) => (
          <div key={n}>
            <h3>{spans(`proof-${n}h`)}</h3>
            <p>{spans(`proof-${n}p`)}</p>
          </div>
        ))}
      </section>

      <section className={`install${rd}`} ref={secRef('install')}>
        <div className="wash wash--ochre" aria-hidden="true" />
        <div>
          <h2>{spans('install-h')}</h2>
          <p className="req">{spans('install-req')}</p>
          {/* TODO: swap for the Chrome Web Store URL once the listing is live */}
          <a className="btn cta" href="#" aria-disabled="true">Add to Chrome — soon</a>
          <p className="reqs">{spans('install-reqs')}</p>
        </div>
        <img className="flyaway" src="/birds/8-flyaway.webp" alt="" aria-hidden="true" />
      </section>
    </>
  );
}
