'use client';
import { useEffect, useRef, useState, useCallback } from 'react';

/**
 * The page reads itself. Audio was generated by the same Kokoro model the
 * extension runs, so the voice on this page IS the product.
 *
 * Two things are driven off the audio clock:
 *   1. which sentence is lit, and how far the signal-rule has swept under it
 *   2. the concentric arcs, driven by real amplitude from an AnalyserNode
 */
export default function Narrator({ sentences, total }) {
  const audioRef = useRef(null);
  const canvasRef = useRef(null);
  const ruleRefs = useRef([]);
  const rafRef = useRef(0);
  const audioCtx = useRef(null);
  const analyser = useRef(null);

  const hero = sentences.filter((s) => s.zone === 'hero');
  const body = sentences.filter((s) => s.zone !== 'hero');
  const heroCount = hero.length;

  const [playing, setPlaying] = useState(false);
  const [idx, setIdx] = useState(-1);
  const [elapsed, setElapsed] = useState(0);
  const idxRef = useRef(-1);      // read inside rAF without re-arming the loop
  const levelRef = useRef(0);     // smoothed amplitude
  const lastTick = useRef(0);

  /* ---- arcs: real amplitude, not a fake sine ---- */
  const draw = useCallback((level) => {
    const cv = canvasRef.current;
    if (!cv) return;
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    const size = cv.clientWidth;
    if (cv.width !== size * dpr) { cv.width = size * dpr; cv.height = size * dpr; }
    const ctx = cv.getContext('2d');
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.clearRect(0, 0, size, size);

    // The arcs open leftward (0.62pi -> 1.38pi), so the drawn mass runs from
    // cx-maxR to cx+coreR, not symmetrically about cx. Centring that span inside
    // the canvas puts the origin right of centre, otherwise the whole field looks
    // shoved to the left with dead space beside it.
    const cx = size * 0.66, cy = size * 0.5;
    const rings = 5;
    for (let i = 0; i < rings; i++) {
      const t = i / (rings - 1);
      const base = size * (0.11 + t * 0.245);
      // outer rings respond more, so the whole field breathes outward
      const r = base * (1 + level * 0.055 * (0.4 + t));
      const a = (0.34 - t * 0.05) * (0.45 + level * 0.85);
      const g = ctx.createLinearGradient(cx - r, cy - r, cx + r, cy + r);
      g.addColorStop(0, `rgba(120,220,221,${a})`);
      g.addColorStop(1, `rgba(143,230,166,${a})`);
      ctx.strokeStyle = g;
      ctx.lineWidth = Math.max(1.5, size * 0.0125 * (1 - t * 0.35));
      ctx.lineCap = 'round';
      ctx.beginPath();
      // open on the right, mirroring the icon
      ctx.arc(cx, cy, r, Math.PI * 0.62, Math.PI * 1.38);
      ctx.stroke();
    }
    // the emitting core
    const cr = size * 0.036 * (1 + level * 0.4);
    const core = ctx.createRadialGradient(cx, cy, 0, cx, cy, cr * 2.4);
    core.addColorStop(0, `rgba(190,245,205,${0.85 * (0.5 + level)})`);
    core.addColorStop(1, 'rgba(143,230,166,0)');
    ctx.fillStyle = core;
    ctx.beginPath(); ctx.arc(cx, cy, cr * 2.4, 0, Math.PI * 2); ctx.fill();
    ctx.fillStyle = `rgba(214,250,224,${0.6 + level * 0.4})`;
    ctx.beginPath(); ctx.arc(cx, cy, cr, 0, Math.PI * 2); ctx.fill();
  }, []);

  /* ---- the clock ---- */
  useEffect(() => {
    const tick = () => {
      const a = audioRef.current;
      let level = 0;
      if (analyser.current) {
        const buf = new Uint8Array(analyser.current.frequencyBinCount);
        analyser.current.getByteTimeDomainData(buf);
        let sum = 0;
        for (let i = 0; i < buf.length; i++) { const v = (buf[i] - 128) / 128; sum += v * v; }
        const rms = Math.sqrt(sum / buf.length);
        // exponential moving average — fast attack, slow release, so the field
        // swells with speech instead of strobing on every frame
        const target = Math.min(1, rms * 2.6);
        const k = target > levelRef.current ? 0.30 : 0.06;
        levelRef.current += (target - levelRef.current) * k;
        level = levelRef.current;
      }
      draw(level);

      if (a && !a.paused) {
        const t = a.currentTime;
        if (t - lastTick.current > 0.25) { lastTick.current = t; setElapsed(t); }
        const i = sentences.findIndex((s) => t >= s.start && t < s.end);
        if (i !== idxRef.current) { idxRef.current = i; setIdx(i); }
        // sweep the rule across the live sentence at the speaking rate
        sentences.forEach((s, k) => {
          const el = ruleRefs.current[k];
          if (!el) return;
          const p = k === i ? Math.min(1, (t - s.start) / (s.end - s.start)) : (t >= s.end ? 1 : 0);
          // the rule is driven straight off the audio clock via refs, so it never
          // waits on a React render
          el.style.transform = `scaleX(${p})`;
        });
      }
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, [draw, sentences]);   // NOT idx — that rebuilt the loop mid-speech

  const toggle = async () => {
    const a = audioRef.current;
    if (!a) return;
    if (a.paused) {
      idxRef.current = -1;
      // AnalyserNode must be wired after a user gesture or the context stays suspended
      if (!audioCtx.current) {
        const AC = window.AudioContext || window.webkitAudioContext;
        audioCtx.current = new AC();
        const src = audioCtx.current.createMediaElementSource(a);
        analyser.current = audioCtx.current.createAnalyser();
        analyser.current.fftSize = 1024;
        src.connect(analyser.current);
        analyser.current.connect(audioCtx.current.destination);
      }
      if (audioCtx.current.state === 'suspended') await audioCtx.current.resume();
      await a.play(); setPlaying(true);
    } else { a.pause(); setPlaying(false); }
  };

  const seek = (i) => {
    const a = audioRef.current; if (!a) return;
    a.currentTime = sentences[i].start + 0.01;
    if (a.paused) toggle();
  };

  const mmss = (s) => `${String(Math.floor(s / 60)).padStart(2,'0')}:${String(Math.floor(s % 60)).padStart(2,'0')}`;

  return (
    <>
      <section className="hero">
        <div className="kicker">Local · Open source · Free forever</div>
        <h1>
          {hero.map((s, i) => (
            <span key={i} className={`sent${idx === i ? ' live' : ''}${idx > i ? ' spoken' : ''}`}
                  onClick={() => seek(i)}>
              {s.text}
              <span className="rule" ref={(el) => (ruleRefs.current[i] = el)} />
              {i < hero.length - 1 ? <br /> : null}
            </span>
          ))}
        </h1>
        <p className="sub">
          A browser extension that speaks web pages in a natural voice. The speech model runs
          on <b>your own computer</b> — not a server. Nothing you read is ever uploaded, and there
          is no account, no API key, and nothing to pay for.
        </p>
        <canvas ref={canvasRef} className="field" aria-hidden="true" />
      </section>

      <section className="passage">
        <div className={`label${playing ? ' live' : ''}`}>
          <span className="dot" />
          {playing ? 'Now speaking — Kokoro-82M, voice af_heart' : 'Press listen. The page will read itself.'}
        </div>

        <div className="controls">
          <button className="listen" onClick={toggle}>
            {playing ? (
              <svg width="12" height="14" viewBox="0 0 12 14" fill="currentColor"><rect width="4" height="14" rx="1.2"/><rect x="8" width="4" height="14" rx="1.2"/></svg>
            ) : (
              <svg width="13" height="15" viewBox="0 0 13 15" fill="currentColor"><path d="M12.2 6.3a.8.8 0 0 1 0 1.4L1.6 14.3A.8.8 0 0 1 .4 13.6V1.4A.8.8 0 0 1 1.6.7z"/></svg>
            )}
            {playing ? 'Pause' : 'Listen'}
          </button>
          <span className="elapsed">{mmss(elapsed)} / {mmss(total)}</span>
        </div>

        <p className="script">
          {body.map((s, k) => {
            const i = k + heroCount;
            return (
              <span
                key={i}
                className={`sent${i === idx ? ' live' : ''}${idx > i ? ' spoken' : ''}`}
                onClick={() => seek(i)}
                title="Read from here"
              >
                {s.text}{' '}
                <span className="rule" ref={(el) => (ruleRefs.current[i] = el)} />
              </span>
            );
          })}
        </p>


        <audio ref={audioRef} src="/audio/narration.mp3" preload="auto"
               onEnded={() => { setPlaying(false); setIdx(-1); idxRef.current = -1; levelRef.current = 0; }} />
      </section>
    </>
  );
}
